README.md
Relative links are broken because the files are missing the ".md" extension.
This change (1) add the extension and (2) removes a broken link.
=> Fix relative links in README.

.github/workflows/ci.yaml, src/plugins/event-plugins/__integ__/WebVitalsPlugin.test.ts
Firefox and Safari currently fail several web vitals browser integration tests. This is because Firefox and Safari do not natively support web vitals.To make CI workflow run without having this error we need to skip these tests if the browser is Safari or Firefox.
1.This change will make WebVitalsPlugin.test.ts to skip if browser is safari or firefox.
2.This change will make CI workflow to run integ tests in firefox and edge.
Manual Testing is done to check whether webvital test is skipped if the browser is safari or firefox.
=> Add webvitals tests to skip if browser is Safari or Firefox

src/__tests__/CommandQueue.test.ts, src/dispatch/__tests__/Authentication.test.ts, src/dispatch/__tests__/BeaconHttpHandler.test.ts, src/dispatch/__tests__/CognitoIdentityClient.test.ts, src/dispatch/__tests__/StsClient.test.ts, src/plugins/event-plugins/__tests__/JsErrorPlugin.test.ts
Resolve https://github.com/aws-observability/aws-rum-web/issues/58
This change fixes handling of rejected promises in Jest tests.  Now (1) these tests no longer fail, and (2) when they do fail, the test that failed is visible (instead of the process crashing).
- Remove `// ts-ignore` in modified files
- Fix test broken by new Node.js error TypeError message format
=> Fix unit test promise assertions.

src/plugins/event-plugins/__tests__/FetchPlugin.test.ts, src/plugins/event-plugins/__tests__/XhrPlugin.test.ts, src/plugins/utils/http-utils.ts
Resolve https://github.com/aws-observability/aws-rum-web/issues/50
This change modifies the behavior of Fetch and XHR X-Ray tracing such that the name of the subsegment defaults to `window.location.hostname` when a hostname cannot be parsed from the request URL.
=> Use location.hostname as subsegment name when path is relative

.github/workflows/cd.yaml
The release workflow is currently not protected by required reviewers or deployment branches.
This change configures the deployment workflow to use the [cdn-prod-release](https://github.com/aws-observability/aws-rum-web/settings/environments) environment. This environment is protected with required reviewers and is restricted to the main branch.
- Bumps Node.js to v16
- I ran a [successful release](https://github.com/qhanam/aws-rum-web/actions/runs/1547181121) from my fork to the [gamma stack](https://client.rum-gamma.us-west-2.amazonaws.com/1.0.3-test/cwr.js).
=> Read cdn release secrets from environment.

.github/workflows/cd.yaml
The current deployment workflow does not publish the package to NPM.
This change adds a step to the deployment workflow which publishes the package to NPM.
- I have verified the workflow publishes the package to NPM by running the workflow with a dummy package name (see https://github.com/qhanam/aws-rum-web/runs/4480893240)
=> Publish to NPM from deployment workflow.

.github/scripts/deploy.sh, .github/workflows/cd.yaml
Some application owners may want to automatically consume new patch versions or minor versions.
This change modifies the deployment workflow to add two files to the CDN: one for applications to automatically consume new patch versions, and one for applications to automatically consume new minor versions.
The folder structure is modeled after [NPM semantic versioning notation](https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept). For example, if the current version is `1.0.3`, the following files will be published to CDN:
`/1.0.3/cwr.js`
`/1.0.x/cwr.js`
`/1.x/cwr.js`
However, if the version is tagged as a non-production release, only the exact version will be published. For example, if the current version is …
=> Add update version types to deployment workflow.

CHANGELOG.md, package.json
Bump version to 1.0.4 and update changelog.
`1.0.3` has been [deprecated in NPM](https://www.npmjs.com/package/aws-rum-web?activeTab=versions) because the published version is inconsistent with GitHub.
`1.0.4` will replace `1.0.3` so that the GitHub, CDN and NPM versions will be consistent.
=> Prepare 1.0.4 release

.github/scripts/deploy.sh
Partially resolves #73 .
This change adds a Cache-Control header to new web client versions deployed to CDN. Specific versions (e.g., `1.0.4`) have a max age of **one week**. Auto-update versions (e.g., `1.0.x` and `1.x`) have a max age of **two hours**, so that impact is limited in case a change needs be be rolled back.
Note that browsers typically cache files by default (using a heuristic to estimate TTL), so this change is non-critical. 
We still need to add Cache-Control headers to the existing CDN files to fully resolve #73. This will be done by directly modifying the header info of the existing files.
I ran the deployment workflow in the gamma environment and verified the header `cache-control: max-age=604800` is present in `1.0.4/cwr.js`, and `cache-control: max-age=7200` is …
=> fix: add Cache-Control max-age to CDN files

docs/cdn_angular.md, docs/cdn_installation.md, docs/cdn_react.md
Noticed a few typos in the documentation as I was reading them. Just fixing those.
---
=> fix: documentation typos

app/delayed_page.html, src/plugins/event-plugins/NavigationPlugin.ts, src/plugins/event-plugins/__integ__/NavigationPlugin.test.ts, src/plugins/event-plugins/__tests__/NavigationPlugin.test.ts, src/test-utils/mock-data.ts
Modified NavigationPlugin to capture PerformanceNavigationEvents when the plugin loads after the page does.
- Removed PerformanceObserver from eventListener.
- Added two new unit test cases and modified existing one case with respect to the new implementation change.
- Created a new app called delayed_page.html that loads the script after the page finishes loading.
- Created a new integ test case using the delayed_page app to verify that PerformanceNavigationEvents are captured.
To test the change, do the following:
- Create a temporary app (delayed_page.html) in your local repository without any other implementation changes
- Run server and either use Chrome debugger or open up local host, compare the output between index.html and delayed_page.html.
- index.html should have the …
=> fix: capture PerformanceNavigationTiming events even when window.load fires before plugin loads

.gitignore, package-lock.json, package.json, src/plugins/event-plugins/__nightwatch__/PageViewPlugin.test.js
A number of test dependencies are flagged by NPM for security risks.
This change applies changes generated by `npm audit fix --force`, and fixes nightwatch tests that were broken by the change.
---
=> Bump nightwatch to 2.0.6.

src/plugins/utils/http-utils.ts
When RUM integrate with X-Ray, RUM was using the terminology `Application`, but then change to `Appmonior`. Raise this PR to keep consistency.
---
=> fix: change RUM origin from AWS::RUM::Application to AWS::RUM::AppMonitor

.prettierignore, CHANGELOG.md, package-lock.json, package.json
Release v1.1.0. Added a build target to execute the [standard-version](https://github.com/conventional-changelog/standard-version) utility. This bumps the version and updates the changelog.
```
npm run version
```
---
=> chore(release): 1.1.0

app/dom_event.html, src/event-schemas/dom-event.json, src/loader/loader-dom-event.js, src/plugins/event-plugins/DomEventPlugin.ts, src/plugins/event-plugins/__integ__/DomEventPlugin.test.ts, src/plugins/event-plugins/__tests__/DomEventPlugin.test.ts
Users currently configure the DOM event plugin to listen to events either with (1) the ID of the DOM element or (2) the actual JavaScript object. However, a customer may want to add a tag to certain elements which should be recorded. There is currently no way to listen for a certain tag.
This feature allows customers to specify listeners for DOM elements using CSS locators.
---
=> feat: identify DOM events using CSS locator

src/plugins/utils/http-utils.ts
According from https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-aws:
> namespace – aws for AWS SDK calls; remote for other downstream calls.
By setting this, xray console service map will treat this node as a AWS service node.
=> fix: set aws api call xray subsegment namespace to aws

.github/scripts/deploy.sh, package.json, webpack/webpack.prod.js
The license banner currently points to a file which is incomplete and which we don't upload to CDN.
This change (1) adds the LICENSE file to CDN and (2) fixes the banner to point to LICENSE and LICENSE-THIRD-PARTY.
---
=> fix: Point to correct license files in bundle banner.

package-lock.json, src/plugins/event-plugins/FetchPlugin.ts, src/plugins/event-plugins/__tests__/FetchPlugin.test.ts, src/plugins/utils/http-utils.ts
When `fetch` is called with a `Request` object as the first argument, the web client overrides the custom http headers in the `Request` object. This is because the web client adds the trace id header to a new `init` argument, which causes existing custom http headers to be overwritten.
This change modifies the behavior of the `fetch` monkey patch such that when `fetch` is called with a `Request` object, the `X-Amzn-Trace-Id` header is added directly to the `Request.header` object, instead of to a new `init` object.
---
=> fix: Set x-amzn-trace-id header directly in request headers

README.md, docs/cdn_angular.md, docs/cdn_installation.md, docs/cdn_react.md, docs/cdn_troubleshooting.md
We have observed several common issues experienced by application owners setting up the RUM web client.
This change adds a troubleshooting guide, which includes these common issues.
This change also fixes several spelling errors in documentation.
=> Add troubleshooting guide to documentation.

.github/scripts/deploy.sh, .github/workflows/cd.yaml
The version in the GitHub release draft created by the deployment process is currently broken, as it was using a manual input value which no longer exists (the version is now read directly from the npm package).
This change fixes the version in the GitHub release draft.
Verified deployment [succeeds in gamma](https://github.com/qhanam/aws-rum-web/actions/runs/1885731865).
---
=> chore: Fix package version in GitHub release tag

.github/scripts/deploy.sh, package-lock.json, webpack/webpack.prod.js
There is currently no source map available to help debug issues with applications integrating the RUM client.
This change adds a hidden source map to the prod webpack build, and uploads the source map to the CDN during deployment.
Verified deployment [succeeds in gamma](https://github.com/qhanam/aws-rum-web/actions/runs/1885731865).
---
=> chore: Add source map to prod build output and CDN.

.github/scripts/deploy.sh
There is currently no way for RUM client CDN consumers to know what the current (stable) version of the RUM web client is. For example, this is important when generating the code snippet which applications use to install the RUM web client.
This change writes the current version to CDN during deployment.
Verified deployment [succeeds in gamma](https://github.com/qhanam/aws-rum-web/actions/runs/1885731865).
---
=> chore: Write current version to CDN

src/plugins/event-plugins/NavigationPlugin.ts, src/plugins/event-plugins/__integ__/NavigationPlugin.test.ts, src/plugins/event-plugins/__integ__/PerformancePlugin.test.ts
Version `1.1.0` and later has a bug which causes `com.amazon.rum.performance_navigation_event.duration` to be `0` when the web client loads before `window.load` has been fired.
Root Cause:
- Window fires `load` when the page has finished loading according to documentations, but there seems to be cases where it is actually fired before the `loadEventEnd` is fired.
- PR #81 correctly fixes the bug that did not capture when the page loads before the plugin does, but by removing PerformanceObserver, we started emitting `navigation_events` as soon as window fired `load`.
- As a result, there are times when `navigation_events` emits 0 for fields such as `duration`, `loadEventEnd`, etc.
This PR addresses the issue by doing the following:
1. No longer rely on callback when the page has already …
=> fix: Use PerformanceObserver to act as a second check to prevent returning 0 for duration and loadEventEnd

CHANGELOG.md, package-lock.json, package.json
Release v1.2.1. Added a build target to execute the [standard-version](https://github.com/conventional-changelog/standard-version) utility. This bumps the version and updates the changelog.
---
=> chore(release): 1.2.1

src/event-schemas/http-event.json, src/plugins/event-plugins/__tests__/FetchPlugin.test.ts, src/plugins/event-plugins/__tests__/XhrPlugin.test.ts
Problem:
- When the web client creates an HTTP event that contains an error, it relies on `errorEventToJsErrorEvent` that creates a `JsErrorEvent` to populate the `error` field in the `http-event`. `JsErrorEvent` by default adds `version`, which does not exist in the webclient's and dataplane's `http-event` schema.
- This was not caught on the web client as the `FetchPlugin` and `XhrPlugin` are unaware of the property details within the `error` object created by `errorEventToJsErrorEvent`.
- As a result, any HTTP events that contains an error was rejected by the dataplane due to this event schema discrepancy.
Fix:
- Dataplane event schema changes have been merged in.
- This PR updates the `http-event` schema to eliminate the schema difference between dataplane and web client and edits …
=> fix: Add version property to http-event-schema

src/plugins/event-plugins/JsErrorPlugin.ts, src/plugins/event-plugins/__tests__/JsErrorPlugin.test.ts, src/plugins/utils/js-error-utils.ts
Problem:
The current implementation to handle `unhandledrejection` events simply assumes that the `PromiseRejectEvent.reason` is a string and populates it under `js-error-event.message` as a string. 
As a result, if the `PromiseRejectEvent.reason` is actually an error object, it does not properly stringify the error object, and instead populates the `js-error-event.message` field with an empty object, `{}`.
This results in the `JsErrorEvent` being rejected by the dataplane, as the `js-error-event.message` field is expected to be a string.
Fix:
This PR addresses the issue by doing two things:
1. Reuse `eventHandler` in `JsErrorPlugin` in `promiseRejectHandler` by extracting the `event.type` and `event.reason` and casting into an `ErrorEvent`.
2. Reuse parsing methods in `js-error-util` to …
=> fix: Parse unhandledrejection error objects

README.md, docs/cdn_commands.md, docs/cdn_installation.md, docs/cdn_troubleshooting.md, docs/configuration.md, docs/npm_installation.md
The RUM web client has been added to one or more ad-block lists. This can disable telemetry for browsers with ad blockers installed.
This change (1) adds documentation on the NPM installation process, and (2) adds guidance to application owners to work around this issue by either hosting the web client bundle as an application assets, or importing the web client into the application code as a JavaScript module.
---
=> docs: Add JS module (npm) install instructions

app/page_event.html, src/CommandQueue.ts, src/__tests__/CommandQueue.test.ts, src/event-cache/EventCache.ts, src/event-cache/__tests__/EventCache.test.ts, src/event-schemas/meta-data.json, src/orchestration/Orchestration.ts, src/orchestration/__tests__/Orchestration.test.ts, src/sessions/PageManager.ts, src/sessions/__integ__/PageManager.test.ts, src/sessions/__tests__/PageManager.test.ts
Users want to add tags to pages so that data from RUM events can be separated into different groups for analysis, metric aggregation, etc. Currently, users are unable to add tags to pages. This feature will allow them to add tags and will store the page tag data in the event metadata. Users can pass in the page tag data:
(1) when manually recording page view events using `recordPageView()`
(2) by manually setting the page tag data using `setCustomAttributes()`
---
=> feat: Page tagging

.github/scripts/deploy.sh
Problem:
- Even though the CloudFront compression settings were correctly in place, the `cwr.js` files uploaded to S3 via GitHub release process had the default mime type of `binary/octet-stream`. As a result, users would always have to download the full sized web client in their applications.
Fix:
- CloudFront does not support compression of `binary/octet-stream`, so this fix adds an extra parameter in the `deploy.sh` for all major/minor/patch web client versions to set the mime type to `text/javascript`.
Test:
- Created a mock release version of 1.4.0 that included the fix and released in Gamma
- All major/minor/patch versions had the mime type of `text/javascript`
- Smoke test file was configured to use web client `v1.4.0`
- The web client's transferred size is 28.74kb instead of …
=> fix: Add content-type in deploy script to support compression

package-lock.json, package.json, playwright.config.ts, playwright.local.config.ts, src/__smoke-test__/dataplane-integ.spec.ts, src/__smoke-test__/ingestion-integ.spec.ts
Problem:
- Currently smoke tests are performed manually, and in order to gain assurance on newly released web client's correct behavior, automated smoke test is required to (1) verify web client recording events and delivering to data plane successfully (2) verify the complete ingestion of recorded events.
This PR:
- As mentioned above, there are two levels of verification. This PR contains the test cases that verify ingestion of events (separate cases by event types).
---
=> test: Create ingestion verification test cases with parallel processing

.gitignore, tsconfig.cjs.json, tsconfig.es.json, tsconfig.json, tsconfig.webpack.json
tsconfigs can extend from each other 
Now if one is updated, the others also will be updated (if need be) based off changes from the root tsconfig
---
=> chore: 🤖 remove duplicate ts configurations and instead extend

src/sessions/VirtualPageLoadTimer.ts, src/sessions/__tests__/VirtualPageLoadTimer.test.ts
Basically the finally call of fetch was not only being called on
finally.
---
=> fix: 🐛 fix issue that decrement fetch counter was called always

.github/workflows/ci.yaml
See docs here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
Prevents multiple runs of a branch running at the same time
---
=> feat: 🎸 cancel ci runs that are currently running on push

.github/workflows/cd.yaml
The current CHANGELOG link that is generated as part of the release workflow is broken/outdated.
This PR changes the CHANGELOG link with the correct path.
---
=> chore: Update CHANGELOG link in GitHub Release workflow

src/orchestration/Orchestration.ts
While merging #156 and #153 , there is a duplicate line of code that initializes `PageIdFormat`, which is breaking all tests that are run as part of CI.
This PR fixes the issue by removing the duplicate initialization.
Tested on local
---
=> fix: Remove duplicate PageIdFormat type in orchestration

docs/cdn_troubleshooting.md
The RUM Web Client supports SPA timing feature as of v1.5.0 release. 
This change (1) adds documentation regarding common questions customers may have regarding the SPA feature (2) adds documentation regarding `sessionEventLimit` under `Events are not being sent by the web client to CloudWatch RUM`
---
=> docs: Add SPA troubleshooting

app/js_error_event.html, docs/configuration.md, package.json, src/loader/loader-js-error-event.js, src/plugins/event-plugins/JsErrorPlugin.ts, src/plugins/event-plugins/__integ__/JsErrorPlugin.test.ts, src/plugins/event-plugins/__tests__/JsErrorPlugin.test.ts
Previously, CW RUM did not provide an option to allow customers to filter out error events that provided no monitoring value. 
This PR addresses the issue by allowing the customers to pass in a function that acts similar to `Array.filter` to indicate whether the error should be recorded or not.
Resolves #119 
Added a new unit test and an integ test to cover the new behavior.
---
=> Ignore errors

app/smoke.html, src/__smoke-test__/ingestion-integ.spec.ts, src/test-utils/smoke-test-utils.ts
Previously in our smoke test, we covered most of the events we generated, except for `CLS_EVENT_TYPE`, `XRAY_TRACE_EVENT_TYPE`, and `DOM_EVENT_TYPE`.
This PR adds these test cases to verify ingestion behavior on the three missing event types and updates the smoke test application accordingly.
---
=> test: Add Xray, DOM, and CLS smoke test cases

src/dispatch/Dispatch.ts, src/dispatch/RetryHttpHandler.ts, src/dispatch/__tests__/Dispatch.test.ts, src/dispatch/__tests__/RetryHttpHandler.test.ts, src/orchestration/Orchestration.ts, src/orchestration/__tests__/Orchestration.test.ts
The RUM web client does not currently have mechanisms to (1) retry failed requests, and (2) cease sending requests when there are repeated failures. This is problematic because repeating failed requests can negatively impact application and is unlikely to change the outcome of the requests.
This change causes the web client to retry failed fetch requests up to three times. If a request fails after three retries, the web client will cease sending data to the CloudWatch RUM service.
For example, failures may include: failure to retrieve credentials (e.g., from cognito/sts), failure to sign request (e.g., from malformed credentials), data plane authentication failure (i.e., 403 response code) and network failures (e.g., poor connectivity).
Related to #21
---
By submitting this pull request, …
=> feat: Retry fetch requests and disable dispatch on failure.

src/plugins/event-plugins/FetchPlugin.ts, src/plugins/event-plugins/XhrPlugin.ts, src/plugins/event-plugins/__tests__/FetchPlugin.test.ts, src/plugins/event-plugins/__tests__/XhrPlugin.test.ts, src/plugins/utils/http-utils.ts
HTTP request and X-Ray trace segments, for both fetch and XHR, do not currently include the URL of the request. The URL is critical for debugging HTTP request failures.
This change adds the URL to http events and trace segments.
---
=> feat: Add request URL to http events and trace segments.

src/plugins/event-plugins/FetchPlugin.ts, src/plugins/event-plugins/XhrPlugin.ts, src/plugins/event-plugins/__tests__/FetchPlugin.test.ts, src/plugins/event-plugins/__tests__/XhrPlugin.test.ts, src/plugins/utils/http-utils.ts, src/test-utils/test-utils.ts
When an error, fault or throttle event occurs, the web client does not currently set the appropriate status flag in the X-Ray segment or subsegment. When viewing the trace in X-Ray, this causes the request to look like it succeeded when it failed.
According to the [X-Ray segment documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-errors):
> Record errors in segments when your application returns an error to the user, and in subsegments when a downstream call returns an error.
This change sets the appropriate `error`, `fault` or `throttle` flag when (1) a 4xx or 5xx status code is returned, or (2) the http request fails.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> fix: Set appropriate error codes in X-Ray segments

src/dispatch/Dispatch.ts, src/dispatch/__tests__/Dispatch.test.ts, src/orchestration/Orchestration.ts, src/orchestration/__tests__/Orchestration.test.ts
When the page transitions to a hidden state and fires the `visibilitychange` event, the page [may be in the process of unloading](https://developer.chrome.com/blog/page-lifecycle-api/), so the web client flushes it's event cache. In this scenario, the approach [recommended by MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) is to use `sendBeacon` so that the request will complete after the page is unloaded. However, ad blockers prevent `sendBeacon` from functioning, so this request may not be sent.
We therefore have two bad options:
1. Use sendBeacon and accept missing data when ad blockers are used and the page loses visibility
2. Use fetch and accept missing data when the page is unloaded before fetch completes
A third option is to send both, …
=> feat: Add useBeacon config for visibilitychange dispatch behavior.

.github/workflows/ci.yaml, src/plugins/event-plugins/FetchPlugin.ts, src/plugins/event-plugins/XhrPlugin.ts, src/plugins/event-plugins/__tests__/FetchPlugin.test.ts
When recording a trace for an http 400, the X-Ray error flag is set on both the root span and the subsegment.
This change removes the error flag from the root span.
---
=> fix: Remove error flag from x-ray trace root.

CHANGELOG.md, package-lock.json, package.json
Releasing a patch to remove error field from X-ray trace events.
---
=> chore(release): 1.8.2

.github/workflows/cd.yaml, .github/workflows/ci.yaml, app/index.html, app/page_event.html, package-lock.json, src/CommandQueue.ts, src/__tests__/CommandQueue.test.ts, src/event-cache/EventCache.ts, src/event-cache/__tests__/EventCache.integ.test.ts, src/event-cache/__tests__/EventCache.test.ts, src/event-schemas/meta-data.json, src/loader/loader-standard.js, src/orchestration/Orchestration.ts, src/orchestration/__tests__/Orchestration.test.ts, src/sessions/PageManager.ts, src/sessions/SessionManager.ts, src/sessions/__integ__/PageManager.test.ts, src/sessions/__integ__/SessionManager.test.ts, src/sessions/__tests__/PageManager.test.ts, src/sessions/__tests__/SessionManager.test.ts
**Context**:
Currently, RUM Web Client does not provide a mechanism to add custom attributes (data in the form of <key, value> pairs) to RUM events. This is problematic because users want to add attributes in addition to the default attributes provided by the RUM event schemas for better data analysis when querying or using the RUM console.
**Changes**:
This PR addresses the problem by doing the following:
1. Allow the web client to accept session attributes during initialization. 
2. Allow the web client to accept session attributes during runtime through the new `addSessionAttributes` API.
3. Allow the web client to accept page attributes during runtime through the existing `recordPageViews` API.
Invalid custom attributes will be excluded from the event metadata. Custom attributes will …
=> feat: Custom attributes

src/plugins/event-plugins/XhrPlugin.ts
An incorrect type argument is causing some builds to fail because of a TypeScript error.
This change fixes the TypeScript error and resolves #218 
Note that enabling TypeScript strict mode (i.e., `"strict": true` in `tsconfig.js`) made the error visible. I don't know why this error isn't visible without strict mode. I did try bumping the TypeScript version.
Issues like this could be prevented by #12.
---
=> fix: Fix MonkeyPatch type arg.

app/page_event.html, src/event-cache/__tests__/EventCache.test.ts, src/orchestration/__tests__/Orchestration.test.ts, src/sessions/PageManager.ts, src/sessions/__tests__/PageManager.test.ts, src/utils/constants.ts
Previously, users would add custom page attributes to page view events by adding them as individual fields into the object sent in the `recordPageView()` command. However, to keep parity with how users send in custom session attributes, this change will allow users to send the custom page attributes together in a separate field.
For example:
```
//Before
{
pageId: '/page_view_two',
pageTags: ['pageGroup1'],
customPageAttributeString: 'customPageAttributeValue',
customPageAttributeNumber: 1,
customPageAttributeBoolean: true
}
```
```
//After
{
pageId: '/page_view_two',
pageTags: ['pageGroup1'],
pageAttributes: {
customPageAttributeString: 'customPageAttributeValue',
customPageAttributeNumber: 1,
customPageAttributeBoolean: true
} 
}
```
---
By submitting this pull request, I confirm that …
=> Refactored recordPageView to add custom attributes in one param

.eslintrc.js, package-lock.json, src/CommandQueue.ts, src/dispatch/Authentication.ts, src/dispatch/CognitoIdentityClient.ts, src/dispatch/Dispatch.ts, src/dispatch/EnhancedAuthentication.ts, src/dispatch/FetchHttpHandler.ts, src/dispatch/RetryHttpHandler.ts, src/dispatch/StsClient.ts, src/event-cache/EventCache.ts, src/index-browser.ts, src/plugins/InternalPlugin.ts, src/plugins/MonkeyPatched.ts, src/plugins/event-plugins/DemoPlugin.ts, src/plugins/event-plugins/DomEventPlugin.ts, src/plugins/event-plugins/FetchPlugin.ts, src/plugins/event-plugins/PageViewPlugin.ts, src/plugins/event-plugins/XhrPlugin.ts, src/plugins/types.ts, src/plugins/utils/http-utils.ts, src/sessions/PageManager.ts, src/sessions/SessionManager.ts, src/sessions/VirtualPageLoadTimer.ts, tsconfig.json
The web client does not currently use TypeScript's strict mode, which provides better type safety.
This change enables strict mode for production code (and resolves strict mode type violations). Strict mode remains disabled for test code.
Resolves #12 .
---
=> chore: Enable typescript strict mode

src/event-cache/EventCache.ts, src/event-cache/__tests__/EventCache.integ.test.ts, src/event-cache/__tests__/EventCache.test.ts, src/sessions/SessionManager.ts
Previously, users could overwrite built-in default attributes. However, this may lead to unexpected behavior in the CW RUM console and poor user experience. This change will ensure that built-int attributes will overwrite any custom attributes if the attribute key is the same.
Changes passed integ tests: https://github.com/limhjgrace/aws-rum-web/pull/1
---
=> fix: Default attributes not overwritten by custom attributes

src/plugins/event-plugins/ResourcePlugin.ts, src/plugins/event-plugins/__tests__/NavigationPlugin.test.ts, src/plugins/event-plugins/__tests__/ResourcePlugin.test.ts, src/test-utils/mock-data.ts
The web client currently ignores resource timings where the resource has the same host name as the RUM data plane endpoint. While this prevents an infinite loop of recording PutRumEvents requests, it is problematic when PutRumEvents requests are proxied through the same endpoint as the application server.
For example, I may have an endpoint which routes the following paths:
1. `https://myapp.amazonaws.com/user`
2. `https://myapp.amazonaws.com/gamma/application/aa17a42c-e737-48f7-adaf-2e0905f48073/events`
In case (1), the request is related to the application logic, and the web client should record the request.
In case (2), the request is related to RUM, and the web client should not record the request.
This change solves the problem by checking the path fragment of the resource URL **in …
=> fix: Only ignore PutRumEvents requests on proxy endpoints.

src/dispatch/Authentication.ts, src/dispatch/CognitoIdentityClient.ts, src/dispatch/StsClient.ts, src/dispatch/__tests__/CognitoIdentityClient.test.ts, src/dispatch/__tests__/StsClient.test.ts, src/dispatch/utils.ts, src/loader/loader-ingestion.js, src/orchestration/Orchestration.ts, src/remote-config/remote-config.ts
Cognito and STS error messages do not currently contain the underlying error.
This change adds the underlying error to the thrown error message.
This change also addresses three other issues in the authentication code:
1. Fix an asynchrony issue where errors weren't being handled by the catch block.
2. Refactor async functions to use async style instead of promise style.
3. Fix linter warnings by adding explicit types to responses.
Resolves #227 and #233.
---
=> fix: Add cause to Cognito and STS error messages

package-lock.json, src/dispatch/DataPlaneClient.ts, src/dispatch/Dispatch.ts, src/dispatch/__tests__/BeaconHttpHandler.test.ts, src/dispatch/__tests__/DataPlaneClient.test.ts, src/dispatch/__tests__/Dispatch.test.ts, src/orchestration/Orchestration.ts, src/orchestration/__tests__/Orchestration.test.ts
When using a proxy, requests need not be signed by SigV4, however, the web client still requires credentials to dispatch requests. A workaround to this has been to add dummy credentials. 
This change adds a `proxy` config option. When `proxy = true`, the web client will dispatch data without waiting for credentials, and without signing requests.
While we could have simply added dummy credentials as a solution, omitting the SigV4 step entirely will allow us to remove this part of the AWS SDK in the future, reducing the size of the web client.
---
=> feat: Omit request signature when in proxy mode.

src/__smoke-test__/ingestion-integ.spec.ts
This PR removes the trailing slash in `TARGET_URL` variable used for all smoke test cases. 
The trailing slash caused the smoke test cases to hang as the request URL never matched with the `TARGET_URL`
##Verification
Successful Smoke Test on v1.11.0 - https://github.com/adebayor123/aws-rum-web/actions/runs/3365000004/jobs/5579997365
---
=> fix: Remove trailing slash in TARGET_URL

src/plugins/event-plugins/FetchPlugin.ts, src/plugins/event-plugins/__tests__/FetchPlugin.test.ts
- When in createHttpEvent, if there is no method on the RequestInit, then try to get the method from the RequestInfo
---
=> fix: Populate method from Request Info

.github/workflows/ci.yaml
The web client CI is breaking because GitHub's Ubuntu 22 image [does not have](https://github.com/actions/runner-images/issues/6399#issuecomment-1302149048) Firefox installed.
GitHub is [planning to add Firefox](https://github.com/actions/runner-images/pull/6528) to its Ubuntu 22 image. In the meantime, this change pins Ubuntu to 20.04 for the web client CI.
---
=> chore: Pin Ubuntu CI image to 20.04.

docs/configuration.md, src/plugins/event-plugins/JsErrorPlugin.ts, src/plugins/event-plugins/__integ__/JsErrorPlugin.test.ts
Presently, the default stack trace length is too short, leading to important stack trace information being truncated. A longer stack trace is crucial for allowing better insight into errors.
This changes increases the default stack trace length for Javascript errors from 200 to 1000. 
---
=> feat: Increase stack trace length

src/sessions/SessionManager.ts, src/sessions/__tests__/SessionManager.test.ts
Presently, session ID is not created in all instances.  Without a session ID, we are unable link events from the same page together. 
This change will allow a session ID to be created in all instances. This allows all events tied to a single page to be linked together. 
---
=> feat: Create a session ID when cookies are disabled

.github/scripts/deploy.sh
Description:
This PR updates the usage of set-output command in GH actions.
Reference : https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
---
=> Update the usage of set-output command in GH actions

app/page_event.html, src/event-schemas/meta-data.json, src/event-schemas/page-view-event.json, src/sessions/PageManager.ts, src/sessions/__integ__/PageManager.test.ts, src/sessions/__tests__/PageManager.test.ts
Currently, AWS CloudWatch RUM does not support referrer. Information about the referrer for page views is not presently available. 
This change adds the ability for the RUM web client to record and dispatch referrer information. The referrer will be stored in the `referrer` field in event details of a page view event. The referrer's domain will be stored in the `referrerDomain` field in event details of a page view event.
---
=> feat:referrer

src/__integ__/cookiesEnabled.test.ts, src/event-schemas/page-view-event.json, src/sessions/PageManager.ts, src/sessions/SessionManager.ts, src/sessions/__integ__/PageManager.test.ts, src/sessions/__tests__/PageManager.test.ts
Currently, AWS CloudWatch RUM does not record the time spent on a certain page. This change records the time spent on a page as part of the `parentTimeSpentOnPage` field in the page view event details. This field records the time spent on the parent page to the page view event it is recorded in.
---
=> feat:Time Spent on Page

src/test-utils/smoke-test-utils.ts
Added the following metadata attributes in the list of built in attributes that smoke test checks against. 
```aws:client```
```aws:clientVersion```
These metadata attributes will be added to every event and therefore need to be included in the list of built in attributes that smoke test verify events against. For more details on why these attributes are added to every event's metadata, refer to [PR](https://github.com/aws-observability/aws-rum-web/pull/321). 
---
=> chore: Add versioning related metadata attributes to smoke test utilities

CHANGELOG.md, package.json
This PR releases 1.13.0
The following changes are made: 
Features:
Create a session ID when cookies are disabled, in order to link all events in a single page together([#314](https://github.com/aws-observability/aws-rum-web/issues/314)) ([6943587](https://github.com/aws-observability/aws-rum-web/commit/6943587259b8d7623742656199dc26b26b5bcd5d))
Increase default stack trace length from 200 to 1000([#313](https://github.com/aws-observability/aws-rum-web/issues/313)) ([28e34c5](https://github.com/aws-observability/aws-rum-web/commit/28e34c5ad541e1fc1e0b12c1a937289df5911791))
Record referrer and referrer's domain ([#327](https://github.com/aws-observability/aws-rum-web/issues/327)) ([a414c92](https://github.com/aws-observability/aws-rum-web/commit/a414c9265b37f9eafe7ae6475fe71357beadbcfc)) …
=> chore(release): 1.13.0

package-lock.json, package.json, webpack/webpack.common.js
The web client bundle has non-ES5 code because the aws-sdk no longer emits ES5. For now we want to continue to emit ES5, because we still want to close gracefully for browsers like IE that are past end-of-life.
This change updates the babel configuration to transform the aws-sdk to ES5.
---
=> fix: Transpile @aws-sdk to ES5.

CHANGELOG.md, package-lock.json, package.json, webpack/webpack.common.js
This PR adds the following fix and bumps the patch version from 1 to 2 (1.13.1 to 1.13.2)
* Transpile @aws-sdk to ES5 to gracefully close browsers at end of life (https://github.com/aws-observability/aws-rum-web/pull/363) ([f63150d](https://github.com/aws-observability/aws-rum-web/commit/f63150df6ed6a9d8a877ccfe8e160c5a8d9873ec))
---
=> chore(release): 1.13.2

src/orchestration/Orchestration.ts, src/orchestration/__tests__/Orchestration.test.ts, src/sessions/PageManager.ts, src/sessions/__tests__/PageManager.test.ts
Automated route change timing requires the web client to monkey patch the HTTP APIs (i.e., fetch and XHR). If other libraries are also patching the HTTP APIs, this could interfere with application behavior.
To fix this problem, this change adds a configuration option to enable/disable route change timing.
---
=> feat: Add config to disable route change timing.

src/index.ts
The `recordPageView` function accepts an argument of type `PageAttributes`, but this type is not exported.
This change exports the `PageAttributes` type.
Resolves #330 
---
=> fix: Export PageAttributes type.

package.json
There is a missing dependency on `@aws-sdk/querystring-builder`, which can break builds.
This change adds that dependency to package.json.
Resolves #328 .
---
=> fix: Add @aws-sdk/querystring-builder as a dependency.

package.json
Update entry point to new `dist/es/src` directory. Related Issue: https://github.com/aws-observability/aws-rum-web/issues/371
---
=> fix: Update entry point in package.json

package.json
Update entry point to new `dist/es/src` directory. Related Issue: https://github.com/aws-observability/aws-rum-web/issues/371
---
=> fix: Update entry point in package.json (#377)

src/sessions/PageManager.ts, src/sessions/__tests__/PageManager.test.ts
This change contains a patch based on customer reported issue, wherein, pageId was missing from the metadata of certain events. 
In a previous [change](https://github.com/aws-observability/aws-rum-web/pull/341) we changed the behavior of when a Page View event is recorded. In cases where  page views resume (this includes resumed sessions and page being reloaded) but page ID is same were changed from being recorded as a separate page view event for each reload/resume to only creating a new page view event only when there was a change in the pageId. However, the change failed to address the following: 
1) In the case when the PageManager's state is restored after being resumed (using the page object stored in cookie), the cookie does not contain PageManager managed attributes which are …
=> fix: Handle missing PageId in metadata when page is resumed

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/general_inquiries.yml
To better categorize our GitHub issues, we will add the following templates:
1. Bug Report
2. Feature Request
3. General Inquiries
We will disable the option to create a blank issue so all issues must use one of the three templates mentioned above. Tested each template by pushing changes to separate branch in forked repo and verifying the generated form. 
---
=> chore: Add GitHub issues templates

.github/scripts/update_smoke_test.sh, .github/workflows/cd.yaml
The release workflow does not currently test the release in a pre-prod environment before executing the release. This means that (1) the release technician must manually test the release in a pre-prod environment before executing a release, and (2) there is an increased risk of a regression.
This change adds steps to the release workflow to test the release in a pre-prod environment before running the release.
This change adds the following three secrets secrets to the release environment.
1. `ROLE_GAMMA`
2. `BUCKET_GAMMA`
3. `CDN_GAMMA`
I've verified the new release workflow succeeds in pre-prod up to the NPM publishing step, which is unchanged. See https://github.com/qhanam/aws-rum-web/actions/runs/5226500122/jobs/9437220189
---
By submitting this pull request, I confirm that my …
=> chore: Run smoke tests in pre-prod before publishing

src/dispatch/CognitoIdentityClient.ts, src/dispatch/EnhancedAuthentication.ts, src/dispatch/__tests__/CognitoIdentityClient.test.ts, src/dispatch/__tests__/EnhancedAuthentication.test.ts
Cognito recently onboarded CloudWatch RUM to its enhanced authflow. However, the enhanced authflow implemented in the web client is currently broken because it uses the identity pool Id, instead of the identity Id, as the argument for `getCredentialsForIdentity`.
This change modifies the enhanced authflow to fetch the identity Id before calling `getCredentialsForIdentity`.
---
=> fix: Add getId to enhanced authflow

src/dispatch/Authentication.ts, src/dispatch/EnhancedAuthentication.ts, src/dispatch/__tests__/Authentication.test.ts, src/dispatch/__tests__/EnhancedAuthentication.test.ts
Currently in our Authentication and EnhancedAuthentication, we save credential object as serialized string values. Then, as we read the serialized string from Storage, we parse the string into a Credential object.
However, in AnonymousStorageCredentialsProvider, we overwrite the local member variable credential with the serialized string instead of the parsed object. As a result, any situation that requires reading of the credential from storage leads to: `TypeError: this.credentials.expiration.getTime is not a function.`
This PR removes the unnecessary step to overwrite the local member `this.credential` with the serialized string.
---
=> fix: Save deserialized credential object to Authentication member

src/dispatch/__tests__/Authentication.test.ts
Addresses the concern from https://github.com/aws-observability/aws-rum-web/pull/436.
> nit: This test will pass under certain conditions when it should fail (i.e., false negative).
> Specifically, when this.credentials.expiration is undefined, and the expiration property of the value returned by AnonymousStorageCredentialsProvider is a Date object. When this happens, control flow will reach AnonymousCognitoCredentialsProvider, and the test needs a way to distinguish the value returned here from the expected value.
> You can fix this by mocking the response of getCredentials, like was done in [EnhancedAuthentication.test.ts here](https://github.com/aws-observability/aws-rum-web/pull/436/files#diff-94a33512cc69b461d93e786b0cfc32e12f8767a11831604e38300860eb1ffba7R348-R355).
---
By …
=> fix: Update false-negative test case in Authentication.test

src/dispatch/CognitoIdentityClient.ts, src/dispatch/__tests__/CognitoIdentityClient.test.ts, src/utils/constants.ts
Cognito identity Ids, which are used to allow unauthenticated users to send RUM data, can be re-used and do not expire.
This change stores identity Ids in localStorage in a similar way to how credentials are stored. Along with using the enhanced authflow, this means in most cases there will be one auth-related request instead of three.
---
=> feat: Re-use Cognito identity id

src/event-bus/EventBus.ts, src/event-bus/__tests__/EventBus.test.ts, src/event-cache/EventCache.ts, src/event-cache/__tests__/EventCache.test.ts, src/orchestration/Orchestration.ts, src/plugins/event-plugins/NavigationPlugin.ts, src/plugins/event-plugins/ResourcePlugin.ts, src/plugins/event-plugins/__tests__/NavigationPlugin.test.ts, src/plugins/event-plugins/__tests__/ResourcePlugin.test.ts, src/plugins/types.ts, src/test-utils/test-utils.ts
> Rewrite of #440 
This PR creates the structure necessary for sharing information between plugins. 
1. Have PluginA find eventId's created by PluginB etc. Useful for LCP attribution
2. WebVitalsPlugin tracks current count of in-flight Xhr and Fetch requests
**Revision 1**
I have created `EventBus` with topic-based filtering. I implemented our own instead of taking on a dependency because we only need a few extremely simple features. 
* Plugins can subscribe to any topic via `context.bus.subscribe(topic, callback)`
* Plugins can publish to any topic via `context.bus.dispatch(topic, message)`
* All events are published on every record by EventCache via `bus.dispatch(eventType, message)`
**Revision 2**
* Plugins are responsible for dispatching events
* EventCache is not responsible for …
=> chore: dispatch all events to EventBus

src/event-schemas/cumulative-layout-shift-event.json, src/event-schemas/first-input-delay-event.json, src/event-schemas/largest-contentful-paint-event.json, src/plugins/event-plugins/WebVitalsPlugin.ts, src/plugins/event-plugins/__integ__/WebVitalsPlugin.test.ts, src/plugins/event-plugins/__tests__/WebVitalsPlugin.test.ts
**Revision 1**
1. Collect attributions for LCP, FID, and CLS
2. Only some fields are captured, ignoring those that are redundant or not relevant for diagnostics
**Revision 2**
**Will be included in another PR**
1. Link CWV attributes to their related Resource and Navigation events
2. Integ test for FID, if possible
---
=> feat: add attributions for core web vitals: LCP, CLS, and FID

src/event-schemas/http-event.json, src/plugins/event-plugins/FetchPlugin.ts, src/plugins/event-plugins/XhrPlugin.ts, src/plugins/event-plugins/__tests__/FetchPlugin.test.ts, src/plugins/event-plugins/__tests__/XhrPlugin.test.ts
There is currently no direct link between HTTP requests and their respective X-Ray traces. This makes it difficult to find the correct X-Ray trace when debugging client-side issues related to HTTP requests.
This change adds the trace Id and segment Id to http request events when tracing is enabled.
---
=> feat: Add trace id to http events

src/plugins/event-plugins/FetchPlugin.ts, src/plugins/event-plugins/XhrPlugin.ts, src/plugins/event-plugins/__tests__/FetchPlugin.test.ts, src/plugins/event-plugins/__tests__/XhrPlugin.test.ts, src/plugins/utils/__tests__/http-utils.test.ts, src/plugins/utils/http-utils.ts
When a CW Synthetics canary has `ActiveTracing` enabled and generates activity on a web application monitored by a CW RUM app monitor that also has `ActiveTracing` enabled, users experience a broken X-Ray trace experience where the segment from the canary to the web application is disconnected from the downstream segments. This is because the RUM Web Client overwrites the X-Ray trace header in the HTTP requests with a new trace while the RUM DataPlane drops activity generated by CW Synthetics canaries (and thus the trace is never created/sent to X-Ray for ingestion). 
This PR will update the Web Client tracing behavior to (1) not trace HTTP requests if the activity is generated by a CW Synthetics canary and (2) not overwrite existing trace headers.
Unit tests should be enough to cover …
=> fix: Avoid overwriting existing trace header

src/plugins/event-plugins/ResourcePlugin.ts, src/plugins/event-plugins/__tests__/ResourcePlugin.test.ts, src/test-utils/mock-data.ts, src/utils/__tests__/common-utils.test.ts, src/utils/common-utils.ts
This is a follow up from an issue spotted in #450 and #448. See https://github.com/aws-observability/aws-rum-web/pull/450#discussion_r1330455383
The ResourcePlugin mislabels `fileType`. Currently, `fileType` maps to buckets of file extensions from `PerformanceResourceTiming.name` (e.g. ".jpg" and ".png" map to "image"). However, file extensions cannot be trusted to exist, such as during redirects. When extensions are missing, events are mislabelled as "other". 
I have considered two solutions:
1. Use [initiatorType](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/initiatorType) to infer fileType when file extension is missing. 
2. Remove the idea of "fileType" altogether and only use initiatorType. 
**My recommendation is (1), which this PR implements.** This is …
=> feat: getResourceType() uses initiatorType when file extension missing

src/plugins/event-plugins/XhrPlugin.ts, src/plugins/event-plugins/__tests__/XhrPlugin.test.ts
closes #452 
XhrPlugin is leaking memory because the internal map is never cleaned. This is causing the web client to be unusable for customers with a high volume of xhr requests. 
---
=> fix: XhrPlugin cleans cache on every record

src/plugins/event-plugins/XhrPlugin.ts, src/plugins/event-plugins/__tests__/XhrPlugin.test.ts
Follow up to https://github.com/aws-observability/aws-rum-web/pull/454#discussion_r1335028410
1. Restores XhrPlugin names, as requested
2. Remove cacheSize() getter, which was only used for testing
---
=> chore: restore XhrPlugin var names

src/plugins/event-plugins/TTIPlugin.ts
An import in the newly released TTI plugin uses an absolute import. This appears to be causing [issues](https://github.com/aws-observability/aws-rum-web/issues/474) with a users' tests. 
This change removes the import entirely as it is unnecessary. 
---
=> fix: Remove unnecessary TTIPlugin import

src/event-cache/EventCache.ts, src/event-cache/__tests__/EventCache.integ.test.ts, src/event-cache/__tests__/EventCache.test.ts, src/orchestration/Orchestration.ts, src/orchestration/__tests__/Orchestration.test.ts, src/sessions/SessionManager.ts, src/sessions/__tests__/SessionManager.test.ts
Currently, the RUM web client retrieves credentials for all sessions even if the `sessionSampleRate` is < 1. In order to reduce the number of unnecessary requests to Cognito and STS, we will only set/retrieve credentials for sessions that are sampled.
To do this, we will call `getSession()` to get the session and verify if it's recorded or not. Currently, a new session is created when we get a session and it doesn't exist. This PR introduces no change to this default behavior as the new boolean variable `createIfNull`, that is checked before creating a new session, is set to `true` by default. We will only set it to `false` when retrieving the session information to determine whether the web client should retrieve credentials.
I also considered checking if the eventCache had events …
=> chore: Only set credentials for sampled sessions

docs/configuration.md, src/event-cache/__tests__/EventCache.integ.test.ts, src/sessions/SessionManager.ts, src/sessions/__tests__/SessionManager.test.ts
Allow the customization of default attributes, excluding the `platformType`. 
Primary use case is overriding the domain reported to RUM to facilitate using the same app monitor across different top-level domains which is not natively supported in RUM configuration.
---
=> feat: allow customization of default attributes

docs/cdn_angular.md
=> docs: fix error handler name in angular docs

src/plugins/event-plugins/NavigationPlugin.ts, src/plugins/event-plugins/__tests__/NavigationPlugin.test.ts, src/test-utils/mock-data.ts
The navigation event schema validates that the `transferSize` field is non-negative. The `transferSize` field is currently calculated by: `headerSize - encodedBodySize`. However, [`headerSize` is 0 if it the resource was instantaneously retrieved from a cache](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/transferSize). This results in a negative `headerSize` and thus, an invalid event that is dropped by CWR DP. 
This PR adds a check to ensure `transferSize` is greater than 0 when calculating the `headerSize`. 
---
=> fix: Record 0 for headerSize if transferSize is 0

src/orchestration/Orchestration.ts, src/plugins/event-plugins/DomEventPlugin.ts, src/plugins/event-plugins/FetchPlugin.ts, src/plugins/event-plugins/NavigationPlugin.ts, src/plugins/event-plugins/ResourcePlugin.ts, src/plugins/event-plugins/XhrPlugin.ts, src/plugins/event-plugins/__tests__/FetchPlugin.integ.test.ts, src/plugins/event-plugins/__tests__/FetchPlugin.test.ts, src/plugins/event-plugins/__tests__/NavigationPlugin.test.ts, src/plugins/event-plugins/__tests__/ResourcePlugin.test.ts, src/plugins/event-plugins/__tests__/XhrPlugin.test.ts, src/plugins/utils/http-utils.ts, src/plugins/utils/performance-utils.ts
Small cleanup, remove 57 lines by leveraging keyword `Partial<Type>`
---
=> chore: reduce size of partial types

.eslintrc.js, src/CommandQueue.ts, src/dispatch/Authentication.ts, src/dispatch/BasicAuthentication.ts, src/dispatch/CognitoIdentityClient.ts, src/dispatch/Dispatch.ts, src/dispatch/EnhancedAuthentication.ts, src/dispatch/StsClient.ts, src/dispatch/__tests__/BasicAuthentication.test.ts, src/dispatch/__tests__/CognitoIdentityClient.test.ts, src/dispatch/__tests__/Dispatch.test.ts, src/dispatch/__tests__/StsClient.test.ts, src/orchestration/Orchestration.ts, src/test-utils/test-utils.ts
Small refactor to share logic between BasicAuthentication and EnhancedAuthentication.
| File                                                |     Before |                        After |
| --------------------------------------------------- | ---------: | ---------------------------: |
| `dist/cjs/dispatch/Authentication.d.ts`             |   `3.2 kB` |       <sup>5%↑</sup>`3.3 kB` |
| `dist/cjs/dispatch/Authentication.js`               |  `10.9 kB` |   <sup>-18.3%↓</sup>`8.9 kB` |
| `dist/cjs/dispatch/BasicAuthentication.d.ts`        |          — |                      `682 B` |
| `dist/cjs/dispatch/BasicAuthentication.js`          |          — |                     `5.9 kB` |
| `dist/cjs/dispatch/EnhancedAuthentication.d.ts`     |   `3.2 kB` |    <sup>-79.4%↓</sup>`655 B` |
| …
=> chore: reduce size of auth modules 

src/dispatch/BasicAuthentication.ts, src/dispatch/CognitoIdentityClient.ts, src/dispatch/EnhancedAuthentication.ts, src/dispatch/__tests__/BasicAuthentication.test.ts, src/dispatch/__tests__/CognitoIdentityClient.test.ts, src/dispatch/__tests__/EnhancedAuthentication.test.ts
When the Cognito identity id (`cwr_i`) is present in localStorage, `GetOpenIdToken` (basic authflow) can fail in a way that is not recoverable (see #497). For example, this can happen when a ResourceNotFound error is returned by Cognito.
This change (1) invalidates the identity Id when Cognito throws an error during basic authflow, (2) extends error handling to unknown errors for both authflows, and (3) adds a re-try mechanism to both authflows.
Resolves #497.
---
=> fix: Invalidate cognito identity and re-try

src/sessions/PageManager.ts, src/sessions/__tests__/PageManager.test.ts
For every page view, the web client updates the `title` attribute with the value in `window.document.title`. This means that  the `title` attribute still cannot be overridden (i.e., #430 did not actually solve #493).
This change allows the `title` attribute to be overridden when `recordPageView` is used.
**Before**
```
document.title = "sensitive";
pageManager.recordPageView({
pageId: '/home',
pageAttributes: {
title: 'override'
}
});
// attributes: { pageId: '/home', title: 'sensitive' }
```
**After**
```
document.title = "sensitive";
pageManager.recordPageView({
pageId: '/home',
pageAttributes: {
title: 'override'
}
});
// attributes: { pageId: '/home', title: 'override' }
```
Options for fixing this include the following.
1. Stop recording the page title.
1. Record title at the start …
=> fix: Allow title override in page attributes

smoke/smoke-test-application-NPM-CJS/src/loader-npm-rum.ts, smoke/smoke-test-application-NPM-ES/src/loader-npm-rum.ts
Remove `guestRoleArn` from rum config to use enhanced auth flow in smoke tests.
=> chore: Update smoke tests to use enhanced auth flow

src/dispatch/Dispatch.ts, src/dispatch/__tests__/Dispatch.test.ts
When dispatch fails with 401, then RUM should keep alive.
RUM backend does not respond with 401 so this is change is not relevant for standard setups. However, some users have setup proxy servers with valid use cases.
For example https://github.com/aws-observability/aws-rum-web/pull/524#issuecomment-2097987765
---
=> fix: keep alive when dispatch fails with 401

src/event-cache/EventCache.ts, src/event-cache/__tests__/EventCache.test.ts
When the event cache is full, then we should drop the latest event and keep the earliest one. Currently, we are dropping the earliest event which causes two problems
1. We are causing performance issues during page load when compute resources are extremely limited. For example, if there are 300 events against a default cache limit of 200 during the initial PutRumEvents batch, then RUM will execute 100x200=20,000 operations shifting out the earliest events, when resources should instead be allocated towards loading the page. 
2. RUM users are missing important telemetries because earlier events tend to be more relevant than later ones. By keeping early events, we are more likely to capture events that attribute to page load performance, such as LCP resources. 
To ensure a good experience …
=> feat: keep earliest event when cache is full

.github/workflows/cd.yaml, .github/workflows/cdn_rollback.yaml, .github/workflows/ci.yaml, .github/workflows/npm_deprecate.yaml
We need to transition from Node16 to Node20 to use GitHub Actions that is used in our release process. Based on the [docs](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), we have to update the node-version to 20.x in the yaml files.
---
=> chore: Update node-version for actions

.gitignore, src/dispatch/DataPlaneClient.ts
The linter is complaining about the deprecated `Credentials` when we should instead use `AwsCredentialIdentity`. These objects are identical in shape so merging this PR will have no logical effect, except to make the linter a little happier. 
---
=> chore: cleanup AwsCredentialIdentity import

package-lock.json, package.json, webpack/webpack.common.js
These changes reduce the size of `cwr.js` from ~230KB to 141KB. The problem is that we are including unused dependencies because our tree shaking is broken. From webpack documentation: https://webpack.js.org/guides/tree-shaking/
> Ensure no compilers transform your ES2015 module syntax into CommonJS modules (this is the default behavior of the popular Babel preset @babel/preset-env - see the [documentation](https://babeljs.io/docs/en/babel-preset-env#modules) for more details).
This PR restores treeshaking by compiling to native ES5 modules instead of CommonJS. 
However, this only fixes the CDN build and does not impact the NPM build in any way. While the CDN build is compiled by webpack and outputs to `build/assets/cwr.js`, the NPM build is managed by `tsc` and outputs to the `dist` …
=> fix: reduce CDN size by tree shaking

.eslintignore, .github/scripts/update_smoke_test.sh, .github/scripts/upload_smoke_test.sh, .github/workflows/cd.yaml, .github/workflows/cdn_rollback.yaml, app/smoke.html, docs/configuration.md, package.json, smoke/smoke-test-application-NPM-CJS/app/smoke.html, smoke/smoke-test-application-NPM-CJS/src/loader-npm-rum-2.ts, smoke/smoke-test-application-NPM-CJS/src/loader-npm-rum.ts, smoke/smoke-test-application-NPM-CJS/webpack/webpack.dev.js, smoke/smoke-test-application-NPM-ES/app/smoke.html, smoke/smoke-test-application-NPM-ES/src/loader-npm-rum-2.ts, smoke/smoke-test-application-NPM-ES/webpack/webpack.dev.js, src/__smoke-test-npm__/dataplane-integ.spec.ts, src/dispatch/Authentication.ts, src/dispatch/BasicAuthentication.ts, src/dispatch/CognitoIdentityClient.ts, src/dispatch/EnhancedAuthentication.ts, src/dispatch/__tests__/BasicAuthentication.test.ts, src/dispatch/__tests__/CognitoIdentityClient.test.ts, src/dispatch/__tests__/EnhancedAuthentication.test.ts, src/orchestration/Orchestration.ts, src/sessions/SessionManager.ts, src/utils/cookies-utils.ts
Multiple AppMonitors from different AWS accounts cannot currently be used on the same page. Because the credential cookie name `cwr_c` is not unique to an AppMonitor, multiple web clients running on the same page attempt to read and store credential info to the same cookie, which would produce incorrect data.
This change uses the existing `cookieAttributes.unique` configuration to add the AppMonitorID as a postfix to the credential cookie `cwr_c`. When used, the credential cookie name will have the format `cwr_c_[AppMonitor Id]`, and multiple web clients sending data to app monitors in different accounts can run on the same page. 
Related FR: https://github.com/aws-observability/aws-rum-web/issues/557
---
By submitting this pull request, I confirm that my contribution is made under the …
=> feat: support unique credential cookie names

tsconfig.webpack.json, webpack/webpack.prod.js
Without this change, the row and column numbers will be wrong when JSErrors are applied to source maps, because they will mapped to the compiled JS files, not the original TS files. 
TypeScript is supposed to output inline source maps for the JS files that they ultimately create. These TS->JS source maps are necessary so that the line number is actually correct when we debug our TS files. Webpack also needs this information so it knows what to include in the final CDN distro. Currently, we are vending the bad source maps to https://client.rum.us-east-1.amazonaws.com/1.x/cwr.js.map; however, the source map distributions are not advertised. 
Documentation for TS -> JS -> Webpack source maps
https://webpack.js.org/guides/typescript/#source-maps
---
By submitting this pull request, I confirm …
=> fix: point source maps to TS files

src/dispatch/DataPlaneClient.ts, src/dispatch/__tests__/DataPlaneClient.test.ts
---
This is fix for https://github.com/aws-observability/aws-rum-web/issues/594 . 
These options are used to create HttpRequest (https://github.com/aws-observability/aws-rum-web/blob/032a9f5561fea8a9789ad934009d46a9d3d7c388/src/dispatch/DataPlaneClient.ts#L76) , which is then used to create the rum URL ( https://github.com/aws-observability/aws-rum-web/blob/032a9f5561fea8a9789ad934009d46a9d3d7c388/src/dispatch/FetchHttpHandler.ts#L70)
=> Use port from endpoint url to create HttpRequestOptions: fix for 594

app/alias_included.html, src/__integ__/aliasIncluded.test.ts, src/dispatch/DataPlaneClient.ts, src/dispatch/Dispatch.ts, src/dispatch/__tests__/Dispatch.test.ts, src/dispatch/dataplane.ts, src/loader/loader-alias.js, src/orchestration/Orchestration.ts, webpack/webpack.dev.js
This PR adds support for the use of alias field to send with PutRumEvents request. Docs will follow in another PR
---
=> feat: Support use of an alias field

.github/workflows/ci.yaml
The Ubantu version we are using for our Github workflows will stop working on 2025-04-01. 
This PR changes the workflow to use latest version automatically. 
Ref: https://github.com/actions/runner-images/issues/11101
---
=> chore: Upgrade ubantu version to replace deprecating version

app/custom_headers.html, docs/configuration.md, src/dispatch/DataPlaneClient.ts, src/dispatch/Dispatch.ts, src/dispatch/__tests__/DataPlaneClient.test.ts, src/loader/loader-custom-headers.js, src/orchestration/Orchestration.ts, src/test-utils/mock-http-custom-headers.ts, webpack/webpack.dev.js
=> ✨ Custom Headers

smoke/smoke-test-application-CDN/smoke.html, smoke/smoke-test-application-NPM-CJS/src/loader-npm-rum.ts, smoke/smoke-test-application-NPM-ES/src/loader-npm-rum.ts
This PR updates smoke tests to send requests with custom headers and increases test coverage to changes made in https://github.com/aws-observability/aws-rum-web/pull/610. 
Ran smoke tests in forked branch and most tests are passing with the exception of the one that verifies ingestion of navigation events: https://github.com/limhjgrace/aws-rum-web/actions/runs/14112183767/job/39533498647
I verified that this test also fails with latest mainline changes so it is most likely that the failing test is not caused by the custom headers change: https://github.com/limhjgrace/aws-rum-web/actions/runs/14097032216. Will be investigating failing smoke test outside the scope of the custom headers PR.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> chore: Update smoke tests to send requests with custom headers

src/dispatch/Dispatch.ts, src/dispatch/__tests__/Dispatch.test.ts
SendBeacon() is the industry standard way to report data AFTER the user closed the page. This thing has never worked for us before because we called it asynchronously inside a promise, meaning the browser rarely ever received the job. 
In addition, this API is becoming increasingly important, because it is becoming a popular pattern to record events locally without ever publishing them to data analytical services (e.g. RUM) until the last possible moment. 
To fix it, you need to call it synchronously so the browser can queue the job. 
1. https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon
2. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Execution_model#job_queue_and_event_loop
This is fairly hard do an integration test for. There is already coverage …
=> fix: call sendBeacon synchronously

docs/configuration.md, package-lock.json, package.json, src/loader/loader-web-vital-event.js, src/orchestration/Orchestration.ts, src/plugins/event-plugins/WebVitalsPlugin.ts, src/plugins/event-plugins/__tests__/WebVitalsPlugin.test.ts, src/plugins/utils/performance-utils.ts
In web-vitals 3.x -> 4.x upgrade, they changed the default strategy for recording CLS to be continually updated throughout the lifespan of the page, and called only on visibilitychange. Previously, they reported this after first input. 
This means CLS 4.x must be deployed along with the `RecordEventOptions` supporting event candidates in #620. 
---
=> revert: web vitals 4.x upgrade, reportAllLCP, and reportAllCLS

package-lock.json, src/sessions/SessionManager.ts, src/sessions/__tests__/SessionManager.test.ts
I was deflaking the session manager tests, and realized the root cause was an off by one error in the session expiration logic. 
These three unit tests were flaky because sessionExpirationTime is set to 0, and sometimes the sessions did not expire because 0 ms elapsed in between calls to getSession(). 
1. when cookies are disabled during runtime and session expires then getSession returns new session
2. when cookies are enabled during runtime and session expires then getSession returns new session
3. when the sessionId cookie expires then a new sessionId is created
Just change the `>` to `>=`
Removed manual time advancements which were being used to force expire the sessions. 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> fix: resolve off by one error in session expiration

src/dispatch/FetchHttpHandler.ts
Chromium based browsers enforce a 65 kb limit when keepalive is enabled. This should not be enabled by default. 
---
=> Revert "feat: fetch with keepalive (#618)"

.github/workflows/npm_deprecate.yaml
The current NPM deprecate workflow does not format the deprecating message correctly and so, only recognizes the first word of the message. For example: https://www.npmjs.com/package/aws-rum-web/v/1.22.0.
This PR will add quotes around the message so that the full message is included. Tested in forked repo that the `npm deprecate` command is formatted correctly: https://github.com/limhjgrace/aws-rum-web/actions/runs/14543965537/job/40806747504
Command now correctly wraps message in quotes:
```
npm deprecate aws-rum-web-experimental@1.9.0-alpha.1 "Testing deprecate command fix"
```
Workflow failed due to NPM token issues. Manually ran the command above and verified it worked: https://www.npmjs.com/package/aws-rum-web-experimental/v/1.9.0-alpha.1
---
By submitting this pull request, I …
=> fix: Add quotes around message to fix npm deprecate command

src/__smoke-test-npm__/ingestion-integ.spec.ts, src/__smoke-test__/ingestion-integ.spec.ts
Add smoke test for INP. This PR does two things:
1. Verifies that INP is recorded when a slow interaction occurs
2. Verifies that INP is ingested 
Test run - https://github.com/williazz/aws-rum-web/actions/runs/14829133324/job/41626963592
---
=> test: add smoke test for INP

src/__smoke-test-npm__/ingestion-integ.spec.ts, src/__smoke-test__/ingestion-integ.spec.ts
Add two smoke tests which were removed because the backend changes were not deployed yet
Since the changes are deployed now we are adding back these tests
Smoke test results: https://github.com/ishajos/aws-rum-web/actions/runs/16451816656/job/46498743808
---
=> chore: add more smoke tests for w3c trace format
