- src/loader/loader.js
> fix: find the first script tag in head instead of the entire document

- package-lock.json
- src/plugins/event-plugins/FetchPlugin.ts
- src/plugins/event-plugins/XhrPlugin.ts
- src/plugins/event-plugins/__tests__/FetchPlugin.test.ts
- src/plugins/event-plugins/__tests__/XhrPlugin.test.ts
Adding a check when `getSession()` returns undefined to avoid JS error and breaking the page.
---
> Fix: Uncaught TypeError: Cannot read the properties of undefined (reading 'record')

- CHANGELOG.md
- package.json
Bump version to 1.0.5 and update changelog.
---
> Prepare 1.0.5 release.

- docs/cdn_react.md
> Fix global function name reference in cdn_react.md

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.5.0-alpha.0

- CHANGELOG.md
- package-lock.json
- package.json
Patch release that contains fix for route change timing on Fetch functions.
---
> chore(release): 1.5.1

- package-lock.json
- package.json
- src/plugins/MonkeyPatched.ts
- src/plugins/event-plugins/FetchPlugin.ts
- src/plugins/event-plugins/PageViewPlugin.ts
- src/plugins/event-plugins/XhrPlugin.ts
- src/sessions/VirtualPageLoadTimer.ts
update MonkeyPatched typings and removed some duplicated code
---
> refactor: 💡 update typings for MonkeyPatched

- package-lock.json
Bump dev dependencies containing vulnerabilities.
---
> chore(deps): bump async ejs jpeg-js and moment

- docs/npm_installation.md
> Fix a broken link.

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.8.1

- src/plugins/event-plugins/XhrPlugin.ts
> Release 1.8.2

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.8.3

- .github/workflows/ci.yaml
- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.9.0

- app/index.html
- app/page_event.html
- src/CommandQueue.ts
- src/__tests__/CommandQueue.test.ts
- src/event-cache/EventCache.ts
- src/event-cache/__tests__/EventCache.integ.test.ts
- src/event-cache/__tests__/EventCache.test.ts
- src/event-schemas/meta-data.json
- src/loader/loader-standard.js
- src/orchestration/Orchestration.ts
- src/orchestration/__tests__/Orchestration.test.ts
- src/sessions/PageManager.ts
- src/sessions/SessionManager.ts
- src/sessions/__integ__/PageManager.test.ts
- src/sessions/__integ__/SessionManager.test.ts
- src/sessions/__tests__/PageManager.test.ts
- src/sessions/__tests__/SessionManager.test.ts
- src/utils/constants.ts
**Context**:
As there were many new commits into the package, needed to cherry-pick custom attribute commits into the most up-to-date main branch.
Merging the custom attributes feature into mainline after an experimental phase. 
Associated PRs:
1. (approved) https://github.com/aws-observability/aws-rum-web/pull/177
2. (approved) https://github.com/aws-observability/aws-rum-web/pull/228
3. (approved) https://github.com/aws-observability/aws-rum-web/pull/253
---
> feat: Custom attributes

- app/smoke.html
- src/__smoke-test__/ingestion-integ.spec.ts
- src/test-utils/smoke-test-utils.ts
Currently, the custom attributes feature doesn't have smoke test to test e2e. This PR will add a test scenario to detect regression.
Smoke tests tested in fork repo release flow: https://github.com/limhjgrace/aws-rum-web/actions/runs/3341540493/jobs/5532996009
---
> chore: Smoke tests for custom attributes feature

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.11.0

- .github/workflows/codeql-analysis.yml
This PR  will add the CodeQL analysis, which helps to discover vulnerabilities across a codebase, with every change that is being pushed.
---
> Add Code QL analysis

- docs/configuration.md
This PR adds documentation as part of changes introduced in #163.
---
> docs: interactionId parameter for interaction telemetry

- src/plugins/event-plugins/__integ__/NavigationPlugin.test.ts
- src/plugins/event-plugins/__tests__/NavigationPlugin.test.ts
- src/sessions/PageManager.ts
- src/sessions/__integ__/SessionManager.test.ts
- src/sessions/__tests__/VirtualPageLoadTimer.test.ts
> Fixed typos in comments

- docs/configuration.md
> Minor doc fix for error filter sample

- src/plugins/event-plugins/JsErrorPlugin.ts
> JsErrorPlugin - add type to recordJsErrorEvent parameter

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.13.3

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.13.4

- CHANGELOG.md
- package-lock.json
- package.json
- src/sessions/PageManager.ts
- src/sessions/__tests__/PageManager.test.ts
> chore(release): 1.13.5

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/general_inquiries.yml
> chore: Add GitHub issues templates

- .prettierignore
- .prettierrc.json
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/cdn_angular.md
- docs/cdn_commands.md
- docs/cdn_installation.md
- docs/cdn_react.md
- docs/cdn_troubleshooting.md
- docs/configuration.md
- docs/examples.md
- docs/npm_installation.md
Make docs a little easier to maintain by formatting them. 
---
> chore: format docs with prettier

- docs/cdn_angular.md
- docs/cdn_commands.md
- docs/cdn_installation.md
- docs/cdn_react.md
- docs/cdn_troubleshooting.md
Cleaning up the docs to use latest version, per request. 
---
> doc: use CDN version 1.x

- package-lock.json
- package.json
Merge this fix into mainline. Already part of release branch. 
Already reviewed here - https://github.com/aws-observability/aws-rum-web/pull/606
---
> fix: Upgrade playwright to latest version to fix release workflow

- src/dispatch/FetchHttpHandler.ts
AWS SDK for javascript and the fetch http handler set fetch keepalive to true by default. We are using a manual implementation of fetch http handler, and should enforce best practices where we can. 
Reading
1. https://github.com/aws/aws-sdk-js-v3/issues/1003
2. https://aws.amazon.com/blogs/developer/http-keep-alive-is-on-by-default-in-modular-aws-sdk-for-javascript/
3. https://developer.mozilla.org/en-US/docs/Web/API/Request/keepalive
---
> feat: fetch with keepalive
